import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Providers from "../context/Context";
import ThemeSwitch from "./ThemeSwitch";
import { ContextProvider } from "@/context/ContextProvider";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Analytics Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jakarta.className}>
        <Providers>
          <ContextProvider>
            <ThemeSwitch />
            {children}
          </ContextProvider>
        </Providers>
      </body>
    </html>
  );
}
